#!/bin/bash
# @(#) Script to maintain gentoo-based docker image for machine learning.

ROOT="${ROOT:-$(dirname $0)}"
source "${ROOT}"/../lib/common.sh

NAME="${NAME:-ml}"
IMAGE="${IMAGE:-kiyoya/ml}"
TAG="${TAG:-latest}"
BUILD_TAG="${BUILD_TAG:-$(date +%Y%m%d)}"

PACKAGES="
  =dev-lang/python-2*
  =dev-lang/python-3*
  dev-python/matplotlib
  dev-python/nltk
  dev-python/numpy
  dev-python/pip
  sci-libs/atlas
  sci-libs/scikits_image
  sci-libs/scikits_learn
  sci-libs/scikits_optimization
  sci-libs/scikits_timeseries
  sci-libs/scipy"


case "${1}" in
build)
  bootstrap_create "${NAME}"
  bootstrap_shell "${NAME}" \
    -c 'echo "USE=\"${USE} lapack\"" >> /etc/portage/make.conf'
  docker cp \
    "${ROOT}"/package.keywords "${NAME}":/etc/portage/package.keywords/ml
  docker cp "${ROOT}"/package.use "${NAME}":/etc/portage/package.use/ml
  bootstrap_emerge "${NAME}" --update --deep --newuse ${PACKAGES}
  bootstrap_shell_chroot "${NAME}" -x <<EOM
  pip install chainer
EOM
  bootstrap_build "${NAME}" "${IMAGE}":"${BUILD_TAG}"
  ;;
promote)
  docker tag "${IMAGE}":"${BUILD_TAG}" "${IMAGE}":latest
  ;;
pull)
  docker pull "${IMAGE}:${TAG}"
  ;;
run)
  docker run -it --rm \
    --log-driver=none \
    --user "$(id -u)":"$(id -g)" \
    -v "$(volpath $(pwd))":/root \
    -w /root \
    "${IMAGE}:${TAG}" /bin/bash
  ;;
*)
  echo "usage: $0 [ build | promote | pull | run ]"
esac
