#!/bin/bash
# @(#) Script to maintain gentoo-based docker image for machine learning.

ROOT="${ROOT:-$(dirname $0)}"
source "${ROOT}"/../lib/common.sh

NAME="${NAME:-ml}"
IMAGE="${IMAGE:-kiyoya/ml}"
TAG="${TAG:-latest}"

PACKAGES="
  =dev-lang/python-2*
  =dev-lang/python-3*
  dev-python/matplotlib
  dev-python/nltk
  dev-python/numpy
  sci-libs/atlas
  sci-libs/scikits_image
  sci-libs/scikits_learn
  sci-libs/scikits_optimization
  sci-libs/scikits_timeseries
  sci-libs/scipy"
# dev-python/pip

case "${1}" in
build)
  BUILD_TAG="${2:-$(date +%Y%m%d)}"

  bootstrap_create "${NAME}"
  bootstrap_shell "${NAME}" \
    -c 'echo "USE=\"${USE} lapack\"" >> /etc/portage/make.conf'
  docker cp \
    "${ROOT}"/package.keywords "${NAME}":/etc/portage/package.keywords/ml
  docker cp "${ROOT}"/package.use "${NAME}":/etc/portage/package.use/ml
  bootstrap_emerge "${NAME}" --update --deep --newuse ${PACKAGES}
  # TODO(kiyoya): It does not work. Need to chroot to /build.
  # bootstrap_shell "${NAME}" \
  #   -ci 'pip install chainer'
  bootstrap_build "${NAME}" "${IMAGE}":"${BUILD_TAG}" \
    -c "CMD ['/bin/sh']"
  bootstrap_clean "${NAME}"
  ;;
down)
  docker stop "${NAME}"
  docker rm "${NAME}"
  ;;
exec)
  docker exec -it \
    --user "$(id -u)":"$(id -g)" \
    "${NAME}" "${@:2}"
  ;;
pull)
  docker pull "${IMAGE}:${TAG}"
  ;;
reload)
  $0 down
  $0 up
  ;;
up)
  docker run -d -it \
    --name "${NAME}" \
    --log-driver=none \
    --user "$(id -u)":"$(id -g)" \
    -v "$(realpath ${HOME})":"${HOME}" \
    "${IMAGE}:${TAG}"
  ;;
*)
  echo "usage: $0 [ build | down | exec | pull | reload | up ]"
esac
