#!/bin/sh

set -e

DATADIR="${DATADIR:-/var/data/drupal}"
IMAGE="${IMAGE:-kiyoya/drupal-fpm}"
NAME="${NAME:-drupal}"
TAG="${TAG:-latest}"

MARIADB="${MARIADB:-mariadb}"

function job_prepare() {
  docker pull "${IMAGE}:${TAG}"
}

function job_start() {
  docker run -d -it \
    --name "${NAME}" \
    --link "${MARIADB}:mysql" \
    -v "${DATADIR}:/var/www/html" \
    "${IMAGE}:${TAG}"
}

function job_stop() {
  docker kill "${NAME}"
  docker rm "${NAME}"
}

case "${1}" in
prepare)
  job_prepare
  ;;
restart)
  job_stop
  job_start
  ;;
start)
  job_start
  ;;
stop)
  job_stop
  ;;
*)
  echo "usage: $0 [ prepare | restart | start | stop ]"
esac
