#!/usr/bin/env python

import subprocess
import time
import urllib2

CHECK_INTERVAL_IN_SECONDS = 5
METADATA_URI = 'http://169.254.169.254/latest/meta-data/spot/termination-time'
RCON = 'docker exec -it ark ./rcon.sh'

def is_instance_safe():
    try:
        response = urllib2.urlopen(METADATA_URI)
        print response
        return False
    except urllib2.HTTPError as e:
        if e.code == 404:
            return True
        raise e


def block_while_instance_is_safe():
    i = 0
    while is_instance_safe():
        i += 1
        if i % 100 == 0:
            print 'Instance is safe'
            i = 0
        time.sleep(CHECK_INTERVAL_IN_SECONDS)


def rcon(*args):
    return subprocess.check_output((RCON,) + args)


if __name__ == '__main__':
    block_while_instance_is_safe()
    print rcon('broadcast', 'Server will be terminated in 60 seconds!')
    time.sleep(30)
    print rcon('broadcast', 'Server will be terminated in 30 seconds!')
    time.sleep(30)
    print rcon('broadcast', 'Saving the world and terminating...')
    print rcon('saveworld')
    print rcon('doexit')
