#!/bin/bash
set -eu

ROOT="$(dirname $0)"/..

DATADIR="${DATADIR:-/var/data/steam}"

NAME="ark"
REPO="kiyoya/steam"
TAG="latest"

RUN_UID="${RUN_UID:-1101}"
RUN_GID="${RUN_GID:-1101}"

docker run -d \
	-h "${NAME}" \
	-p 7777:7777/udp \
	-p 7778:7778/udp \
	-p 27015:27015/udp \
	--name "${NAME}" \
	--restart always \
	--user "${RUN_UID}":"${RUN_GID}" \
	-v "${DATADIR}":/steam/Steam \
	-w /steam/Steam/ShooterGame \
	"${REPO}":"${TAG}" \
	./Binaries/Linux/ShooterGameServer TheIsland?listen \
		-log \
		-nosteamclient \
		-server

sleep 10
while true; do
	"${ROOT}"/aws/spot-termination-time && break
done

RCON="${ROOT}"/ark/rcon
"${RCON}" broadcast 'Server will be terminated in 60 seconds!'
sleep 30

"${RCON}" broadcast 'Server will be terminated in 30 seconds!'
sleep 30
"${RCON}" broadcast 'Saving the world and terminating...'
"${RCON}" saveworld
"${RCON}" doexit
