#!/bin/sh

set -e

NAME="${NAME:-kiyoya}"
IMAGE="${IMAGE:-kiyoya/docker-kiyoya}"
TAG="${TAG:-latest}"

function job_enter() {
  docker exec -i -t "${NAME}" /docker-init.sh kiyoya
}

function job_prepare() {
  docker pull "${IMAGE}:${TAG}"
}

function job_start() {
  docker run -d -i -t \
    --name "${NAME}" \
    --net=host \
    -v /home:/home \
    "${IMAGE}:${TAG}" /bin/sh
}

function job_stop() {
  docker kill "${NAME}"
  docker rm "${NAME}"
}

case "${1}" in
enter)
  job_enter
  ;;
prepare)
  job_prepare
  ;;
restart)
  job_stop
  job_start
  ;;
start)
  job_start
  ;;
stop)
  job_stop
  ;;
*)
  echo "usage: $0 [ enter | prepare | restart | start | stop ]"
esac
