#!/bin/sh

set -e

DATADIR="${DATADIR:-/var/data/murmur}"
IMAGE="${IMAGE:-kiyoya/murmur}"
NAME="${NAME:-murmur}"
TAG="${TAG:-latest}"

function job_prepare() {
  docker pull "${IMAGE}:${TAG}"
}

function job_start() {
  docker run -d \
    -p 64738:64738 \
    -p 64738:64738/udp \
    --name "${NAME}" \
    -v "${DATADIR}/murmur.ini:/etc/murmur/murmur.ini:ro" \
    -v "${DATADIR}/murmur.sqlite:/var/lib/murmur/murmur.sqlite" \
    "${IMAGE}:${TAG}"
}

function job_stop() {
  docker kill "${NAME}"
  docker rm "${NAME}"
}

case "${1}" in
prepare)
  job_prepare
  ;;
restart)
  job_stop
  job_start
  ;;
start)
  job_start
  ;;
stop)
  job_stop
  ;;
*)
  echo "usage: $0 [ prepare | restart | start | stop ]"
esac
