#!/bin/bash
# @(#) Script to maintain gentoo-based docker image for daily use.
set -eu

source "$(dirname $0)"/../bootstrap.sh

NAME="${NAME:-gentoo}"
REPO="${REPO:-kiyoya/gentoo}"
TAG="${TAG:-latest}"

BUILD_NAME="${BUILD_NAME:-build-"${NAME}"}"
BUILD_TAG="${BUILD_TAG:-$(date +%Y%m%d)}"

PACKAGES="
	app-editors/vim
	app-misc/screen
	app-shells/zsh
	dev-util/cmake
	dev-vcs/git"


case "${1:-}" in
build)
	bootstrap_create "${BUILD_NAME}"
	bootstrap_shell "${BUILD_NAME}" -c 'cat >> /etc/portage/make.conf' <<-EOM
		USE="\${USE} zsh-completion"
	EOM
	bootstrap_package_use "${BUILD_NAME}" <<-EOM
		app-editors/vim python
		dev-python/numpy lapack
	EOM
	bootstrap_emerge "${BUILD_NAME}" \
		--update --deep --newuse ${PACKAGES}
	bootstrap_build "${BUILD_NAME}" "${REPO}":"${BUILD_TAG}"
	;;
promote)
	docker_promote "${REPO}":"${BUILD_TAG}"
	;;
pull)
	docker pull "${REPO}":"${TAG}"
	;;
run)
	docker run -it --rm \
		-h "${NAME}" \
		--log-driver=none \
		--user "$(id -u)":"$(id -g)" \
		-v "$(volumepath $(pwd))":/root \
		-w /root \
		"${REPO}":"${TAG}" /bin/zsh
	;;
vim)
	docker run -it --rm \
		-h "${NAME}" \
		--log-driver=none \
		--user "$(id -u)":"$(id -g)" \
		-e "HOME=${HOME}" \
		-v "$(volumepath ${HOME})"/.vim:"${HOME}"/.vim \
		-v "$(volumepath ${HOME})"/.vimrc:"${HOME}"/.vimrc \
		-v "$(volumepath $(pwd))":/work \
		-w "/work" \
		"${REPO}":"${TAG}" vim "${@:2}"
	;;
*)
	echo "usage: $0 [ build | promote | pull | run ]" 1>&2
	exit 1
esac
