#!/bin/sh

set -eu

NAME="${NAME:-gentoo}"
IMAGE="${IMAGE:-kiyoya/gentoo}"
TAG="${TAG:-latest}"

MY_UID="${MY_UID:-$(id -u)}"
MY_GID="${MY_GID:-$(id -g)}"
MY_USER="${MY_USER:-$(whoami)}"
MY_HOME="${MY_HOME:-${HOME}}"

function job_down() {
  docker stop "${NAME}"
  docker rm "${NAME}"
}

function job_enter() {
  docker exec -i -t "${NAME}" /bin/bash
}

function job_pull() {
  docker pull "${IMAGE}:${TAG}"
}

function job_up() {
  docker run -d -i -t \
    --name "${NAME}" \
    --net=host \
    -e "MY_UID=${MY_UID}" \
    -e "MY_GID=${MY_GID}" \
    -e "MY_USER=${MY_USER}" \
    -e "MY_HOME=${MY_HOME}" \
    -v "${MY_HOME}/.screen" \
    -v "${MY_HOME}:${MY_HOME}" \
    --restart always \
    "${IMAGE}:${TAG}"
}

case "${1}" in
down)
  job_down
  ;;
enter)
  job_enter
  ;;
pull)
  job_pull
  ;;
reload)
  job_down
  job_up
  ;;
up)
  job_up
  ;;
*)
  echo "usage: $0 [ down | enter | pull | reload | up ]"
esac
