#!/bin/bash
# @(#) Script to maintain gentoo-based docker image for daily use.

ROOT="${ROOT:-$(dirname $0)}"
source "${ROOT}"/../bootstrap.sh

NAME="${NAME:-gentoo}"
REPO="${REPO:-kiyoya/gentoo}"
TAG="${TAG:-latest}"
BUILD_TAG="${BUILD_TAG:-$(date +%Y%m%d)}"

PACKAGES="
  app-editors/vim
  app-misc/screen
  app-shells/zsh
  dev-python/pip
  dev-util/cmake
  dev-vcs/git
  net-libs/nodejs"


case "${1}" in
build)
  bootstrap_create "${NAME}"
  bootstrap_shell "${NAME}" \
    -c 'echo "USE=\"${USE} zsh-completion\"" >> /etc/portage/make.conf'
  bootstrap_package_use "${NAME}" "${ROOT}"/package.use
  bootstrap_emerge "${NAME}" --update --deep --newuse ${PACKAGES}
  bootstrap_shell_chroot "${NAME}" <<EOM
    set -eu
    pip install awscli
    npm install -g bower polyserve react-tools
EOM
  bootstrap_build "${NAME}" "${REPO}":"${BUILD_TAG}"
  ;;
promote)
  docker_promote "${REPO}":"${BUILD_TAG}"
  ;;
pull)
  docker pull "${REPO}":"${TAG}"
  ;;
run)
  docker run -it --rm \
    -h "${NAME}" \
    --log-driver=none \
    --user "$(id -u)":"$(id -g)" \
    -v "$(volpath $(pwd))":/root \
    -w /root \
    "${REPO}":"${TAG}" /bin/bash
  ;;
*)
  echo "usage: $0 [ build | promote | pull | run ]"
esac


function job_up() {
  docker run -d -i -t \
    --name "${NAME}" \
    --net=host \
    --log-driver=none \
    -e "MY_UID=${MY_UID}" \
    -e "MY_GID=${MY_GID}" \
    -e "MY_USER=${MY_USER}" \
    -e "MY_HOME=${MY_HOME}" \
    -v "${MY_HOME}/.screen" \
    -v "${MY_HOME}:${MY_HOME}" \
    --restart always \
    "${REPO}:${TAG}"
}

case "${1}" in
down)
  job_down
  ;;
enter)
  job_enter
  ;;
pull)
  job_pull
  ;;
reload)
  job_down
  job_up
  ;;
up)
  job_up
  ;;
*)
  echo "usage: $0 [ down | enter | pull | reload | up ]"
esac
