#!/bin/sh

groupadd -g "${MY_GID}" "${MY_USER}"
useradd -u "${MY_UID}" -d "${MY_HOME}" -g "${MY_USER}" -G wheel -s /bin/zsh "${MY_USER}"
chown "${MY_USER}" "${MY_HOME}/.screen"
chmod 0700 "${MY_HOME}/.screen"
exec >/dev/tty 2>/dev/tty </dev/tty
sudo -u "${MY_USER}" -i -- screen -xRUO
