#!/usr/bin/env python

import sys
import time
from urllib2 import urlopen

METADATA_URI = 'http://169.254.169.254/latest/meta-data/spot/termination-time'
INTERVAL_IN_SECONDS = 5


def get_spot_termiation_time(interval_in_seconds):
    while True:
        try:
            return urllib2.urlopen(METADATA_URI).read()
        except urllib2.HTTPError as e:
            if e.code != 404:
                sys.stderr.write('%s\n' % e)
            time.sleep(interval_in_seconds)


if __name__ == '__main__':
    print get_spot_termination_time(INTERVAL_IN_SECONDS)
