#!/bin/sh

set -eu

DATADIR="${DATADIR:-/var/data/nginx}"
IMAGE="${IMAGE:-nginx}"
NAME="${NAME:-nginx}"
TAG="${TAG:-latest}"

DRUPAL="${DRUPAL:-drupal}"

function job_down() {
  docker stop "${NAME}"
  docker rm "${NAME}"
}

function job_pull() {
  docker pull "${IMAGE}:${TAG}"
}

function job_up() {
  docker run -d -it \
    -p 80:80 \
    --name "${NAME}" \
    -v "${DATADIR}/nginx.conf:/etc/nginx/nginx.conf:ro" \
    -v "${DATADIR}/log:/var/log/nginx" \
    -v "${DATADIR}/html:/var/html:ro" \
    --restart always \
    "${IMAGE}:${TAG}"
}

case "${1}" in
down)
  job_down
  ;;
pull)
  job_pull
  ;;
reload)
  job_down
  job_up
  ;;
up)
  job_up
  ;;
*)
  echo "usage: $0 [ down | pull | reload | up ]"
esac
