#!/bin/sh

set -eu

DATADIR="${DATADIR:-/var/data/mariadb}"
IMAGE="${IMAGE:-mariadb}"
NAME="${NAME:-mariadb}"
TAG="${TAG:-10}"

function job_down() {
  docker stop "${NAME}"
  docker rm "${NAME}"
}

function job_sql() {
  docker exec -it "${NAME}" mysql -u root -p "${DATABASE}"
}

function job_sql_stdio() {
  docker exec -i "${NAME}" mysql -u root --password="${MYSQL_ROOT_PASSWORD}" "${DATABASE}"
}

function job_pull() {
  docker pull "${IMAGE}:${TAG}"
}

function job_init() {
  docker run -it --rm \
    --name "${NAME}" \
    -v "${DATADIR}:/var/lib/mysql" \
    -e MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}" \
    "${IMAGE}:${TAG}"
}

function job_up() {
  docker run -d -it \
    --name "${NAME}" \
    -v "${DATADIR}:/var/lib/mysql" \
    --restart=always \
    "${IMAGE}:${TAG}"
}

case "${1}" in
down)
  job_down
  ;;
init)
  job_init
  ;;
pull)
  job_pull
  ;;
reload)
  job_down
  job_up
  ;;
sql)
  job_sql
  ;;
sql_stdio)
  job_sql_stdio
  ;;
up)
  job_up
  ;;
*)
  echo "usage: $0 [ down | init | pull | reload | sql | sql_stdio | up ]"
esac
