#!/bin/sh

set -e

DATADIR="${DATADIR:-/var/data/mariadb}"
IMAGE="${IMAGE:-mariadb}"
NAME="${NAME:-mariadb}"
TAG="${TAG:-10}"

function job_sql() {
  docker exec -it "${NAME}" mysql -u root -p "${DATABASE}"
}

function job_sql_stdio() {
  docker exec -i "${NAME}" mysql -u root --password="${MYSQL_ROOT_PASSWORD}" "${DATABASE}"
}

function job_prepare() {
  docker pull "${IMAGE}:${TAG}"
}

function job_init() {
  docker run -it --rm \
    --name "${NAME}" \
    -v "${DATADIR}:/var/lib/mysql" \
    -e MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}" \
    "${IMAGE}:${TAG}"
}

function job_start() {
  docker run -d -it \
    --name "${NAME}" \
    -v "${DATADIR}:/var/lib/mysql" \
    "${IMAGE}:${TAG}"
}

function job_stop() {
  docker kill "${NAME}"
  docker rm "${NAME}"
}

case "${1}" in
init)
  job_init
  ;;
prepare)
  job_prepare
  ;;
restart)
  job_stop
  job_start
  ;;
sql)
  job_sql
  ;;
sql_stdio)
  job_sql_stdio
  ;;
start)
  job_start
  ;;
stop)
  job_stop
  ;;
*)
  echo "usage: $0 [ init | prepare | restart | sql | sql_stdio | start | stop ]"
esac
