#!/bin/sh
# @(#) Script to build and maintain gentoo-based openvpn docker images.

set -eu

DATADIR="${DATADIR:-/var/data/openvpn}"
IMAGE="${IMAGE:-kiyoya/openvpn}"
NAME="${NAME:-openvpn}"
TAG="${TAG:-latest}"

BOOT="$(dirname $0)"/../bootstrap.sh

PACKAGES="
  app-crypt/easy-rsa
  net-firewall/iptables
  net-misc/openvpn
  sys-apps/coreutils"


function job_build() {
  "${BOOT}" create "${NAME}"
  "${BOOT}" emerge "${NAME}" ${PACKAGES}
  "${BOOT}" cp "${NAME}" \
    "$(dirname $0)"/docker-entrypoint.sh /build/docker-entrypoint.sh
  "${BOOT}" build "${NAME}" "${IMAGE}:${TAG}" \
    -c 'CMD ["/docker-entrypoint.sh"]' \
    -c 'VOLUME ["/etc/openvpn"]' \
    -c 'EXPOSE 1194' \
    -c 'EXPOSE 1194/udp'
  "${BOOT}" clean "${NAME}"
}

function job_down() {
  sudo docker stop "${NAME}"
  sudo docker rm "${NAME}"
}

function job_pull() {
  docker pull "${IMAGE}:${TAG}"
}

function job_up() {
  sudo docker run -d -it \
    -p 443:443 \
    -p 443:443/udp \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    --name "${NAME}" \
    -v "${DATADIR}:/etc/openvpn:ro" \
    --restart always \
    "${IMAGE}:${TAG}"
}

case "${1}" in
build)
  job_build
  ;;
down)
  job_down
  ;;
pull)
  job_pull
  ;;
reload)
  job_down
  job_up
  ;;
up)
  job_up
  ;;
*)
  echo "usage: $0 [ build | down | pull | reload | up ]"
esac
