#!/bin/bash
# @(#) Script to maintain gentoo-based docker image for openvpn.

ROOT="${ROOT:-$(dirname $0)}"
source "${ROOT}"/../lib/common.sh

DATADIR="${DATADIR:-/var/data/openvpn}"
IMAGE="${IMAGE:-kiyoya/openvpn}"
NAME="${NAME:-openvpn}"
TAG="${TAG:-latest}"
BUILD_TAG="${BUILD_TAG:-$(date +%Y%m%d)}"

PACKAGES="
  app-crypt/easy-rsa
  net-firewall/iptables
  net-misc/openvpn
  sys-apps/coreutils"


case "${1}" in
build)
  bootstrap_create "${NAME}"
  bootstrap_emerge "${NAME}" ${PACKAGES}
  docker cp \
    "${ROOT}"/docker-entrypoint.sh "${NAME}":/build/docker-entrypoint.sh
  bootstrap_build "${NAME}" "${IMAGE}":"${BUILD_TAG}" \
    -c "CMD /docker-entrypoint.sh" \
    -c "VOLUME /etc/openvpn" \
    -c "EXPOSE 1194" \
    -c "EXPOSE 1194/udp"
  bootstrap_clean "${NAME}"
  ;;
down)
  sudo docker stop "${NAME}"
  sudo docker rm "${NAME}"
  ;;
logs)
  sudo journalctl CONTAINER_NAME="${NAME}"
  ;;
promote)
  docker tag "${IMAGE}":"${BUILD_TAG}" "${IMAGE}":latest
  ;;
pull)
  docker pull "${IMAGE}:${TAG}"
  ;;
reload)
  $0 down
  $0 up
  ;;
up)
  sudo docker run -d -it \
    -p 1194:1194/udp \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    --name "${NAME}" \
    -v "${DATADIR}":/etc/openvpn:ro \
    --restart always \
    --log-driver=journald \
    "${IMAGE}:${TAG}"
  ;;
*)
  echo "usage: $0 [ build | down | logs | promote | pull | reload | up ]"
esac
