#!/bin/sh

set -eu

DATADIR="${DATADIR:-/var/data/openvpn}"
IMAGE="${IMAGE:-kiyoya/openvpn}"
NAME="${NAME:-openvpn}"
TAG="${TAG:-latest}"

function job_down() {
  sudo docker stop "${NAME}"
  sudo docker rm "${NAME}"
}

function job_pull() {
  docker pull "${IMAGE}:${TAG}"
}

function job_up() {
  sudo docker run -d -it \
    -p 1194:1194/udp \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    --name "${NAME}" \
    -v "${DATADIR}:/etc/openvpn:ro" \
    --restart always \
    "${IMAGE}:${TAG}"
}

case "${1}" in
down)
  job_down
  ;;
pull)
  job_pull
  ;;
reload)
  job_down
  job_up
  ;;
up)
  job_up
  ;;
*)
  echo "usage: $0 [ down | pull | reload | up ]"
esac
