#!/bin/bash
# @(#) Script to maintain gentoo-based docker image for murmur.

ROOT="${ROOT:-$(dirname $0)}"
source "${ROOT}"/../lib/common.sh

DATADIR="${DATADIR:-/var/data/murmur}"
IMAGE="${IMAGE:-kiyoya/murmur}"
NAME="${NAME:-murmur}"
TAG="${TAG:-latest}"
BUILD_TAG="${BUILD_TAG:-$(date +%Y%m%d)}"

PACKAGES="media-sound/murmur"


case "${1}" in
build)
  bootstrap_create "${NAME}"
  docker cp "${ROOT}"/package.use "${NAME}":/etc/portage/package.use/murmur
  bootstrap_emerge "${NAME}" ${PACKAGES}
  bootstrap_build "${NAME}" "${IMAGE}:${BUILD_TAG}" \
    -c "ENV HOME /var/lib/murmur" \
    -c "EXPOSE 64738" \
    -c "EXPOSE 64738/udp"
  ;;
down)
  docker stop "${NAME}"
  docker rm "${NAME}"
  ;;
logs)
  sudo journalctl CONTAINER_NAME="${NAME}" "${@:2}"
  ;;
promote)
  docker tag "${IMAGE}":"${BUILD_TAG}" "${IMAGE}":latest
  ;;
pull)
  docker pull "${IMAGE}:${TAG}"
  ;;
reload)
  $0 down
  $0 up
  ;;
up)
  docker run -d \
    -p 64738:64738 \
    -p 64738:64738/udp \
    --name "${NAME}" \
    -v "${DATADIR}"/murmur.ini:/etc/murmur/murmur.ini:ro \
    -v "${DATADIR}"/murmur.sqlite:/var/lib/murmur/murmur.sqlite \
    --restart always \
    --log-driver=journald \
    "${IMAGE}:${TAG}" /usr/bin/murmurd -fg -ini /etc/murmur/murmur.ini
  ;;
*)
  echo "usage: $0 [ build | down | logs | promote | pull | reload | up ]"
esac
